version: '3'

services:
    nginx:
        image: nginx:1.16.1
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"  
        volumes:
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/bijay/html:/var/www/html
        links:
            - php
            - mysql
        
    php:
        build: ./server
        image: magento-php:7.2-fpm
        container_name: php
        restart: always
        volumes:
            - ./server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /home/bijay/html:/var/www/html
           
    mysql:
        image: mysql:5.7
        container_name: mysql       
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: f4m5kyb8R34zx5a
            MYSQL_USER: Bijay
            MYSQL_PASSWORD: 5hKh5EVswD
            MYSQL_DATABASE: magento
        volumes:
            - /var/lib/mysql:/var/lib/mysql
