version: '3'

services:
    nginx:
        image: nginx:1.16.1
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/bijay/html/magento:/var/www/html/magento
        depends_on:
            - php
            - mysql
        
    php:
        build: ./php
        image: magento-php:7.2-fpm
        container_name: php
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /home/bijay/html/magento:/var/www/html/magento    
            - /home/bijay/.composer:/root/.composer
           
    mysql:
        image: mysql:5.7
        container_name: mysql       
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: f4m5kyb8R34zx5a
            MYSQL_USER: Bijay
            MYSQL_PASSWORD: 5hKh5EVswD
            MYSQL_DATABASE: magento
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf

    elasticsearch:
        image: elasticsearch:6.8.0
        container_name: elasticsearch       
        ports: 
            - "9200:9200"
        environment:
            ES_JAVA_OPTS: -Xms256m -Xmx256m
        volumes:
            - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

    redis:
        image: redis:5.0.7
        container_name: redis       
        ports: 
            - "6379:6379"
        volumes:
            - /var/lib/redis:/data
        sysctls:
            net.core.somaxconn: 1024
