version: '3'

services:
    nginx:
        image: nginx:1.18.0
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./server/nginx/magento.sample:/etc/nginx/conf.d/magento.sample
            - /home/$user/html/magento:/var/www/html/magento
        depends_on:
            - php
            - mysql
        
    php:
        build: ./server/php
        image: magento-php:7.4-fpm
        container_name: php
        environment:
            COMPOSER_ALLOW_SUPERUSER : 1
        volumes:
            - ./server/php/php-fpm.ini:/usr/local/etc/php/conf.d/php-fpm.ini
            - ./server/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
            - /home/$user/html/magento:/var/www/html/magento    
            - /home/$user/.composer:/root/.composer
           
    mysql:
        image: mysql:8.0.22
        container_name: mysql       
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: f4m5kyb8R34zx5a
            MYSQL_USER: $user
            MYSQL_PASSWORD: 5hKh5EVswD
            MYSQL_DATABASE: magento
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - ./server/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        command: --default-authentication-plugin=mysql_native_password
        cap_add:
            - SYS_NICE

    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch       
        ports: 
            - "9200:9200"
        environment:
            ES_JAVA_OPTS: -Xms256m -Xmx256m
            discovery.type: single-node
        volumes:
            - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

    redis:
        image: redis:5.0.10
        container_name: redis       
        ports: 
            - "6379:6379"
        volumes:
            - /var/lib/redis:/data
        sysctls:
            net.core.somaxconn: 1024
