version: '3.7'

services:
    nginx:
        image: nginx:1.18.0
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/magento.sample:/etc/nginx/conf.d/magento.sample
        depends_on:
            - php
        
    php:
        build: ./php
        image: php:7.4-magento
        container_name: php
        volumes:
            - ./php/php-fpm.ini:/usr/local/etc/php/conf.d/php-fpm.ini
            - /home/$HOST_USER/.composer:/var/www/.composer
           
    mysql:
        image: mariadb:10.4.17
        container_name: mysql       
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - /var/lib/mysql:/var/lib/mysql

    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch       
        ports: 
            - "9200:9200"
        environment:
            ES_JAVA_OPTS: $ES_JAVA_OPTS
            discovery.type: single-node
        volumes:
            - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

    redis:
        image: redis:5.0.10
        container_name: redis       
        ports: 
            - "6379:6379"
        volumes:
            - /var/lib/redis:/data
        sysctls:
            net.core.somaxconn: 1024