version: '3.7'

services:
    nginx:
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/$HOST_USER/html/magento:/var/www/html/magento
    
    php:
        volumes:
            - ./php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
            - /home/$HOST_USER/html/magento:/var/www/html/magento